### ISSUE TITLE
Website changed, scraper failing.

### ISSUE THREAD

**Issue by JasonThomasData** [planningalerts-scrapers/Brimbank_City_Council#1]
The council remade the website.
New addresses and structure to deal with.
I'm still working on other projects now so might not get to this for some time.

**Comment by LoveMyData** [comment]
New link is here: http://www.brimbank.vic.gov.au/building-and-planning/current-advertised-applications

However, council no more publish the council_reference

**Comment by JasonThomasData** [comment]
True, and also the council used to publish each application on a separate page, but now it's all in one page.

**Comment by LoveMyData** [comment]
New link is here: https://www.brimbank.vic.gov.au/advertised-plans

**Comment by JasonThomasData** [comment]
Thanks, I keep meaning to do something about this. I'll b busy for a while but it's on my radar.

**Comment by henare** [comment]
Fixed in #2.
